- name: Install couchapp
  pip: name=couchapp

- name: Install Argos
  git: repo={{ git_repo }}
       dest={{ argos_dir }}

- name: Init couchapp
  command: "couchapp init"
  args:
    chdir: "{{ argos_dir }}"

- name: Configure Couchdb with Argos models
  command: "couchapp push {{ couchdb_url }}/argos"
  args:
    chdir: "{{ argos_dir }}"  